### PR TITLE
First pass on bunyad youtube video compat

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- Filters the bit of Largo that returns the featured media for a post to instead use the video set in the `_bunyad_featured_video` post meta, if that's set.

A post that has a video: http://borderzine.com/2019/05/sisterhood-of-the-traveling-boots-that-began-as-beto-orourke-promotion-absolutely-the-funnest-thing-2/

That same post on staging: http://borderzine.flywheelsites.com/2019/05/sisterhood-of-the-traveling-boots-that-began-as-beto-orourke-promotion-absolutely-the-funnest-thing-2/

With this change:

Screen Shot 2019-09-25 at 12 43 49

## Why

For #24 

## Testing/Questions

Features that this PR affects:

- article pages when the article has `_bunyad_featured_video` metadata

Questions that need to be answered before merging:

- [ ]  Is there a better way to output the YouTube video? Right now we're outputting unescaped, potentially-unsafe raw HTML. It would be nice to use WordPress' oembed get functionality to convert the stored HTML into a known-safe iframe, but it's not clear if WordPress' oembed parser parses URLs that are actually iframes
    <iframe width="640" height="360" src="https://www.youtube.com/embed/EbjxpVAi-v4?rel=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
- [x] This doesn't provide a way for posts to set, change, or remove the `_bunyad_featured_video` metadata. And since the meta key starts with an underscore, it doesn't show up in the "Custom fields" box in the editor, so it can't be edited that way. Should we work on that?

Steps to test this PR:

1. Check out post 34942

### CODE REVIEW

**Comment by benlk** [comment]
Screen Shot 2019-09-25 at 13 11 59

This grey bar comes from a combination of:
- the `margin-bottom: 24px` on `.hero`
- the grey background on `.hero`
- the lack of any caption information within `<div class="embed-details wp-caption"></div>`

Easiest solution is to remove the grey background, which is something we've talked about in Largo at some point in the past.

**Comment by benlk** [comment]
Screen Shot 2019-09-25 at 13 15 13

**Comment by benlk** [comment]
Removing the grey background affects all heros; here's an example on a post with a featured image:

Screen Shot 2019-09-25 at 13 19 35
Screen Shot 2019-09-25 at 13 19 39

**Comment by joshdarby** [comment]
Works as expected so far.

> This doesn't provide a way for posts to set, change, or remove the _bunyad_featured_video metadata. And since the meta key starts with an underscore, it doesn't show up in the "Custom fields" box in the editor, so it can't be edited that way. Should we work on that?

I would think so. Do we know how they have been adding/changing/removing them on their current prod site?

**Comment by benlk** [comment]
Based on some googling, I think it's built into that theme? The theme's documentation http://theme-sphere.com/smart-mag/documentation/#post-formats describes a video post format that seems to match this feature. There's a custom meta box that exposes a place where embed codes can be pasted in.

**Comment by joshdarby** [comment]
> This doesn't provide a way for posts to set, change, or remove the _bunyad_featured_video metadata. And since the meta key starts with an underscore, it doesn't show up in the "Custom fields" box in the editor, so it can't be edited that way. Should we work on that?

@benlk, I spoke with @kaylima in our 1:1 about this and she mentioned that it should be fine if they have to use a new way going forward to add new featured videos to posts, even if it's just in the post content. The main issue was getting the existing videos to show, which you've done, so I think this is good!

**Comment by benlk** [comment]
The Largo featured video doesn't override the `_bunyad_featured_video` option, though. If it's set, it overrides Largo, and there isn't a way to unset it without going in on the DB.

Should we make the Largo featured video override `_bunyad_featured_video`?

**Comment by benlk** [comment]
Kay reports that this is fine.

**Pull request merged**
