### PR TITLE
Adds a `homepage middle 1x3 2nd` widget area

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Duplicates the `Homepage Middle 1x3` widget area to a new one named `Homepage Middle 1x3 2nd`

screencapture-borderzine-test-2019-10-03-12_14_07

## Why

For #64

## Testing/Questions

Features that this PR affects:

- Homepage widget area

Questions that need to be answered before merging:

- [ ] Is this PR targeting the correct branch in this repository?
- [ ] What can we name this that's better than `Homepage Middle 1x3 2nd`?

Steps to test this PR:

1. Duplicate the widgets in the `Homepage Middle 1x3` widget area but with the `Voces & Blogs` category instead of `Diversity and Ideas`
2. Verify it displays exactly like the `Diversity and Ideas` widget area

### CODE REVIEW

**Comment by joshdarby** [comment]
Note: for #65 we are going to make the News & Art sections look like the Diversity and Voices sections, so I'm going to add work for #65 in this PR instead of a separate one.

**Comment by joshdarby** [comment]
https://github.com/INN/umbrella-borderzine/pull/71/commits/8e339a077ec0ecf41201228b049b836d824f711a recreates the top 4x4 widget area to be 2 separate 1x3 areas for #65, making the first 4 widget areas after the featured area to be the 1x3 layout.

New testing instructions (since all of the widget areas are renamed so their existing widgets will be gone):
For each `Homepage Middle n 1x3` widget area:
 - [ ] Add a `Largo recent posts` widget
 - [ ] Give it a title of the category for this widget area. In order, they should be News, Art & Cultura, Immigration & Fronteras, Voices
- [ ] Number of posts -> 1
- [ ] Avoid duplicate posts
- [ ] Thumbnail image -> Large
- [ ] Excerpt Display -> Default 2 sentences
- [ ] Show byline
- [ ] Hide publish date
- [ ] Limit to category mentioned above

- [ ] Add a second `Largo Recent Posts` widget
- [ ] Set title to an empty space
- [ ] Number of posts -> 3
- [ ] Avoid duplicate posts
- [ ] Thumbnail image -> Medium
- [ ] Excerpt Display -> None
- [ ] Show byline
- [ ] Hide publish date
- [ ] Limit to same category as the first widget

screencapture-borderzine-test-2019-10-03-14_27_21

**Comment by benlk** [comment]
Seems to work, and the code checks out.

**Comment by joshdarby** [comment]
@benlk Is this ok to merge?

**Pull request merged**
